// SET ARRAY CHAMPION LIST
const championList = [ { name: "Aatrox", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Aatrox.png?v=v8" },
{ name: "Ahri", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Ahri.png?v=v8" },
{ name: "Akali", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Akali.png?v=v8" },
{ name: "Alistar", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Alistar.png?v=v8" },
{ name: "Amumu", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Amumu.png?v=v8" },
{ name: "Anivia", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Anivia.png?v=v8" },
{ name: "Annie", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Annie.png?v=v8" },
{ name: "Aphelios", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Aphelios.png?v=v8" },
{ name: "Ashe", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Ashe.png?v=v8" },
{ name: "AurelionSol", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/AurelionSol.png?v=v8" },
{ name: "Azir", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Azir.png?v=v8" },
{ name: "Bard", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Bard.png?v=v8" },
{ name: "Blitzcrank", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Blitzcrank.png?v=v8" },
{ name: "Brand", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Brand.png?v=v8" },
{ name: "Braum", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Braum.png?v=v8" },
{ name: "Caitlyn", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Caitlyn.png?v=v8" },
{ name: "Camille", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Camille.png?v=v8" },
{ name: "Cassiopeia", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Cassiopeia.png?v=v8" },
{ name: "Chogath", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Chogath.png?v=v8" },
{ name: "Corki", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Corki.png?v=v8" },
{ name: "Darius", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Darius.png?v=v8" },
{ name: "Diana", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Diana.png?v=v8" },
{ name: "DrMundo", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/DrMundo.png?v=v8" },
{ name: "Draven", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Draven.png?v=v8" },
{ name: "Ekko", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Ekko.png?v=v8" },
{ name: "Elise", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Elise.png?v=v8" },
{ name: "Evelynn", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Evelynn.png?v=v8" },
{ name: "Ezreal", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Ezreal.png?v=v8" },
{ name: "Fiddlesticks", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Fiddlesticks.png?v=v8" },
{ name: "Fiora", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Fiora.png?v=v8" },
{ name: "Fizz", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Fizz.png?v=v8" },
{ name: "Galio", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Galio.png?v=v8" },
{ name: "Gangplank", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Gangplank.png?v=v8" },
{ name: "Garen", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Garen.png?v=v8" },
{ name: "Gnar", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Gnar.png?v=v8" },
{ name: "Gragas", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Gragas.png?v=v8" },
{ name: "Graves", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Graves.png?v=v8" },
{ name: "Hecarim", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Hecarim.png?v=v8" },
{ name: "Heimerdinger", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Heimerdinger.png?v=v8" },
{ name: "Illaoi", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Illaoi.png?v=v8" },
{ name: "Irelia", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Irelia.png?v=v8" },
{ name: "Ivern", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Ivern.png?v=v8" },
{ name: "Janna", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Janna.png?v=v8" },
{ name: "JarvanIV", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/JarvanIV.png?v=v8" },
{ name: "Jax", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Jax.png?v=v8" },
{ name: "Jayce", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Jayce.png?v=v8" },
{ name: "Jhin", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Jhin.png?v=v8" },
{ name: "Jinx", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Jinx.png?v=v8" },
{ name: "Kaisa", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Kaisa.png?v=v8" },
{ name: "Kalista", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Kalista.png?v=v8" },
{ name: "Karma", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Karma.png?v=v8" },
{ name: "Karthus", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Karthus.png?v=v8" },
{ name: "Kassadin", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Kassadin.png?v=v8" },
{ name: "Katarina", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Katarina.png?v=v8" },
{ name: "Kayle", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Kayle.png?v=v8" },
{ name: "Kayn", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Kayn.png?v=v8" },
{ name: "Kennen", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Kennen.png?v=v8" },
{ name: "Khazix", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Khazix.png?v=v8" },
{ name: "Kindred", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Kindred.png?v=v8" },
{ name: "Kled", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Kled.png?v=v8" },
{ name: "KogMaw", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/KogMaw.png?v=v8" },
{ name: "Leblanc", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Leblanc.png?v=v8" },
{ name: "LeeSin", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/LeeSin.png?v=v8" },
{ name: "Leona", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Leona.png?v=v8" },
{ name: "Lillia", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Lillia.png?v=v8" },
{ name: "Lissandra", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Lissandra.png?v=v8" },
{ name: "Lucian", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Lucian.png?v=v8" },
{ name: "Lulu", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Lulu.png?v=v8" },
{ name: "Lux", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Lux.png?v=v8" },
{ name: "Malphite", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Malphite.png?v=v8" },
{ name: "Malzahar", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Malzahar.png?v=v8" },
{ name: "Maokai", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Maokai.png?v=v8" },
{ name: "MasterYi", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/MasterYi.png?v=v8" },
{ name: "MissFortune", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/MissFortune.png?v=v8" },
{ name: "Mordekaiser", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Mordekaiser.png?v=v8" },
{ name: "Morgana", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Morgana.png?v=v8" },
{ name: "Nami", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Nami.png?v=v8" },
{ name: "Nasus", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Nasus.png?v=v8" },
{ name: "Nautilus", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Nautilus.png?v=v8" },
{ name: "Neeko", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Neeko.png?v=v8" },
{ name: "Nidalee", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Nidalee.png?v=v8" },
{ name: "Nocturne", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Nocturne.png?v=v8" },
{ name: "Nunu", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Nunu.png?v=v8" },
{ name: "Olaf", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Olaf.png?v=v8" },
{ name: "Orianna", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Orianna.png?v=v8" },
{ name: "Ornn", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Ornn.png?v=v8" },
{ name: "Pantheon", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Pantheon.png?v=v8" },
{ name: "Poppy", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Poppy.png?v=v8" },
{ name: "Pyke", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Pyke.png?v=v8" },
{ name: "Qiyana", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Qiyana.png?v=v8" },
{ name: "Quinn", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Quinn.png?v=v8" },
{ name: "Rakan", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Rakan.png?v=v8" },
{ name: "Rammus", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Rammus.png?v=v8" },
{ name: "RekSai", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/RekSai.png?v=v8" },
{ name: "Renekton", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Renekton.png?v=v8" },
{ name: "Rengar", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Rengar.png?v=v8" },
{ name: "Riven", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Riven.png?v=v8" },
{ name: "Rumble", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Rumble.png?v=v8" },
{ name: "Ryze", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Ryze.png?v=v8" },
{ name: "Sejuani", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Sejuani.png?v=v8" },
{ name: "Senna", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Senna.png?v=v8" },
{ name: "Sett", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Sett.png?v=v8" },
{ name: "Shaco", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Shaco.png?v=v8" },
{ name: "Shen", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Shen.png?v=v8" },
{ name: "Shyvana", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Shyvana.png?v=v8" },
{ name: "Singed", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Singed.png?v=v8" },
{ name: "Sion", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Sion.png?v=v8" },
{ name: "Sivir", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Sivir.png?v=v8" },
{ name: "Skarner", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Skarner.png?v=v8" },
{ name: "Sona", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Sona.png?v=v8" },
{ name: "Soraka", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Soraka.png?v=v8" },
{ name: "Swain", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Swain.png?v=v8" },
{ name: "Sylas", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Sylas.png?v=v8" },
{ name: "Syndra", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Syndra.png?v=v8" },
{ name: "TahmKench", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/TahmKench.png?v=v8" },
{ name: "Taliyah", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Taliyah.png?v=v8" },
{ name: "Talon", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Talon.png?v=v8" },
{ name: "Taric", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Taric.png?v=v8" },
{ name: "Teemo", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Teemo.png?v=v8" },
{ name: "Thresh", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Thresh.png?v=v8" },
{ name: "Tristana", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Tristana.png?v=v8" },
{ name: "Trundle", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Trundle.png?v=v8" },
{ name: "Tryndamere", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Tryndamere.png?v=v8" },
{ name: "TwistedFate", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/TwistedFate.png?v=v8" },
{ name: "Twitch", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Twitch.png?v=v8" },
{ name: "Udyr", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Udyr.png?v=v8" },
{ name: "Urgot", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Urgot.png?v=v8" },
{ name: "Varus", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Varus.png?v=v8" },
{ name: "Vayne", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Vayne.png?v=v8" },
{ name: "Veigar", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Veigar.png?v=v8" },
{ name: "Velkoz", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Velkoz.png?v=v8" },
{ name: "Vi", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Vi.png?v=v8" },
{ name: "Viktor", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Viktor.png?v=v8" },
{ name: "Vladimir", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Vladimir.png?v=v8" },
{ name: "Volibear", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Volibear.png?v=v8" },
{ name: "Warwick", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Warwick.png?v=v8" },
{ name: "Wukong", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/MonkeyKing.png?v=v8" },
{ name: "Xayah", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Xayah.png?v=v8" },
{ name: "Xerath", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Xerath.png?v=v8" },
{ name: "XinZhao", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/XinZhao.png?v=v8" },
{ name: "Yasuo", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Yasuo.png?v=v8" },
{ name: "Yone", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Yone.png?v=v8" },
{ name: "Yorick", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Yorick.png?v=v8" },
{ name: "Yuumi", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Yuumi.png?v=v8" },
{ name: "Zac", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Zac.png?v=v8" },
{ name: "Zed", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Zed.png?v=v8" },
{ name: "Ziggs", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Ziggs.png?v=v8" },
{ name: "Zilean", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Zilean.png?v=v8" },
{ name: "Zoe", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Zoe.png?v=v8" },
{ name: "Zyra", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Zyra.png?v=v8" },
];

// SET ARRAY TALKS
const talkList = [
    {msg: "Nice to meet you!" },
    {msg: "They won't like this at all." },
    {msg: "Finish them, Pix!" },
    {msg: "Let's use ALL colors!" },
    {msg: "Very high ... Very very high." },
    {msg: "A giggle should fix the problem." },
    {msg: "I'm going on one foot and going back on the other." },
    {msg: "Just a pinch ..."},
    {msg: "Yeah, it tastes a little purple!" },
    {msg: "You'll be able to see better with your eyes closed"},
    {msg: "Oh ... I'm dizzy!" },
    {msg: "Nosy dew!" },
    {msg: "Never look directly at a tulip ..."},
    {msg: "I know this squirrel from somewhere." },
    {msg: "How about a spin? Whoa, whoa whoa ah, ihaha!" },
    {msg: "We need to think straight! Hmm ... hmmhmm ... Ah! Got it"},
    {msg: "Come on, let's dance! Ha!" },
    {msg: "Let's go for another ride! Ha!" },
    {msg: "This battle will be my masterpiece." },
    {msg: "Cut back on their courage." },
    {msg: "With each slaughter the victory approaches." },
    {msg: "There will be no withdrawal." },
    {msg: "Fight or be forgotten." },
    {msg: "Honor will not save you." },
    {msg: "Break and fall." },
    {msg: "Teach them to fear us." },
    {msg: "Now we're playing the game!" },
    {msg: "Plant the seeds of discord"},
    {msg: "Roar against the dying light and don't shine." },
    {msg: "Violence is elegance." },
    {msg: "The pain is temporary, the victory is eternal!" },
    {msg: "Peace is the greatest of lies." },
    {msg: "War reveals what is within us." },
    {msg: "Overcome the fragility of your form." },
    {msg: "They will greet you like heroes." },
    {msg: "True warriors are born in blood!" },
    {msg: "I am as timeless as war." },
    {msg: "Let fear become fury!" },
    {msg: "I know what lurks in the hearts of men." },
    {msg: "Hesitation is death." },
    {msg: "Nobody understands me! They even call me a farm butcher." },
    {msg: "This is not just a massacre. It is my masterful work!" },
    {msg: "Fight and be remembered like a hero, or die and be remembered like a coward." },
    {msg: "Fight like a hero, or die like a coward." },
    {msg: "Fight and be remembered, or die and be forgotten." },
    {msg: "Die in fear in your heart, or win with blood on your hands." },
    {msg: "Even those who have nothing can give their lives." },
    {msg: "Speech not organized by event that initiates it. Grunts and individual sounds have been excluded." },
    {msg: "This is not for hanging on the wall." },
    {msg: "I hope you know how to use this." },
    {msg: "I don't accept returns." },
    {msg: "If you want a gun, here it is. If you want to talk, here's a gun." },
    {msg: "Use this right, you won't regret it." },
    {msg: "Ornn tested, Ornn approved." },
    {msg: "That doesn't mean we are friends." },
    {msg: "A good ax, knocks down trees. A big ax, knocks down armies." },
    {msg: "The weapons I create have no name, they have ambition." },
    {msg: "This is a weapon, you know, to fight." },
    {msg: "You seem to deserve this, don't let me down." },
    {msg: "This is what good means." },
    {msg: "It's for wielding, not for playing." },
    {msg: "I was also watching this one." },
    {msg: "I didn't do anything, and you didn't buy anything, okay?" },
    {msg: "That's enough!" },
    {msg: "Don't move!" },
    {msg: "Forging nerves of steel!" },
    {msg: "I'm going to turn you to dust!" },
    {msg: "Even my beard is angry!" },
    {msg: "It's time for the anvil!" },
    {msg: "Hold my beer!" },
    {msg: "What a beautiful beating!" },
    {msg: "This is how shame is created!" },
    {msg: "Nose, present you the hammer!" },
    {msg: "It will be music for my"}
]